### ISSUE TITLE
TreeKDE doesn't implement variable bandwidths

### ISSUE THREAD

**Issue by dkludwig** [tommyod/KDEpy#58] opened 2020-08-06 15:37 UTC
Hi @tommyod! Thanks for the fast, well-documented package! I'd been searching around for a bit trying to find implementations that allowed for weights AND variable bandwidths, so this was very helpful.

However, while apparently TreeKDE is supposed to be able to handle variable bandwidths, for me just uses the maximum of that list as a fixed bandwidth. I spent ~4 hours trying to figure out why my adaptive KDE's (a la Silverman) were looking exactly like over-smoothed fixed KDE's, and then I realized I should try the NaiveKDE class (which I had been ignoring since from the speed description, the TreeKDE was supposed to be superior) and it worked perfectly.

I just installed KDEpy via pip two days ago, so I don't think there's a version issue, and from looking through past issues I don't think has come up before. I tried deciphering the implementation itself, and what tipped me off to what was happening was that *maximal_bw = np.max(self.bw)*  was being used. Here's some code where I input a list of bandwidths to both NaiveKDE and TreeKDE, where the list is constant except for one, large bandwidth:

```python
import numpy as np
from KDEpy import NaiveKDE, TreeKDE
import matplotlib.pyplot as plt
from scipy.stats import lognorm

fig, axs = plt.subplots(2, 1, figsize=(9, 12))

# get a list of 1000 random variables from the scipy lognormal
# distribution with shape parameter 0.6
rvs = np.sort(lognorm.rvs(0.6, size=1000))
axs[0].plot(rvs, np.repeat(-0.01,len(rvs)), '|r', markersize=5, label='data')
axs[1].plot(rvs, np.repeat(-0.01,len(rvs)), '|r', markersize=5, label='data')

# get pdf of lognormal distribution
x = np.linspace(0, 7, 200)
pdf = lognorm.pdf(0.6, x)
axs[0].plot(x, pdf, 'r', alpha=0.5, label='Actual PDF')
axs[1].plot(x, pdf, 'r', alpha=0.5, label='Actual PDF')

# use a Silverman's long-tailed bandwidth as global_bw
IQR = np.percentile(rvs, q=75) - np.percentile(rvs, q=25)
global_bw = 0.79*IQR*len(rvs)**(-0.2)

# do fixed bandwidth kde's
fixed_naive_kde = NaiveKDE(kernel='gaussian', bw=global_bw).fit(rvs).evaluate(x)
fixed_tree_kde = TreeKDE(kernel='gaussian', bw=global_bw).fit(rvs).evaluate(x)
axs[0].plot(x, fixed_naive_kde, 'g', label='Fixed bandwidth NaiveKDE')
axs[0].plot(x, fixed_tree_kde, ':b', lw=3, label='Fixed bandwidth TreeKDE')

# input an array of bandwidths with only one NOT equal to global_bw
bws = np.repeat(global_bw, len(rvs))
bws[-10] = 10*bws[-10]

var_naive_kde = NaiveKDE(kernel='gaussian', bw=bws).fit(rvs).evaluate(x)
var_tree_kde = TreeKDE(kernel='gaussian', bw=bws).fit(rvs).evaluate(x)
axs[1].plot(x, var_naive_kde, 'g', label='Variable bandwidth NaiveKDE')
axs[1].plot(x, var_tree_kde, 'b', lw=3, label='Variable bandwidth TreeKDE')

# compare to using the max of the variable bandwidths as the fixed bandwidth
max_tree_kde = TreeKDE(kernel='gaussian', bw=np.max(bws)).fit(rvs).evaluate(x)
axs[1].plot(x, max_tree_kde, ':m', lw=3, label='KDE using max')

axs[0].legend()
axs[1].legend()
plt.show()
```
![TreeKDE variable bandwidths](https://user-images.githubusercontent.com/69001870/89551472-fc0f7280-d7d8-11ea-9413-3e385be08e4f.jpeg)

**Comment by tommyod** [comment] 2020-08-06 17:53
Thanks for the well written issue @dkludwig . Most likely it's a documentation error by me, or some error in the code. I'll have to dig a little bit when I find time. If you want to investigate a bit and create a PR, you're very welcome. I can add you to a list of authors. I might not have time to look at this immediately.

**Comment by dkludwig** [comment] 2020-08-07 10:35
No worries! I can look into a little bit, but truthfully this may be out of my pay-grade, seeing as a I really don't truly understand how the TreeKDE implementation even works. I'll give it a shot, though.

**Comment by tommyod** [comment] 2020-11-26 17:13
Hi again @dkludwig . I apologize that this took so long. When I run your code (I changed `b` to  `:b` in `axs[1].plot(x, var_tree_kde, ':b', lw=3, label='Variable bandwidth TreeKDE')`), I get this result, which seems fine.

My version:
```
>>> python -c "import KDEpy; print(KDEpy.__version__)"
1.0.10
>>> python --version
3.7.7
```

Am I missing something?

![image](https://user-images.githubusercontent.com/10076072/100377894-7d9e4100-3012-11eb-866d-b9ff95a63441.png)

**Comment by tommyod** [comment] 2020-11-26 17:20
Hi @dkludwig . 

I apologize that this took so long. I am on Python 3.7.7 and KDEpy 1.0.10:
```
>>> python --version
3.7.7
>>> python -c "import KDEpy; print(KDEpy.__version__)"
1.0.10
```

When I run your code (only changing the marker from `b` to `:b` in the second plot), I get a different plot:
![image](https://user-images.githubusercontent.com/10076072/100378677-d7ebd180-3013-11eb-9f5e-2c142a7e6388.png)

I also tried changing the bandwidths in the line `bws = 2 - np.abs(np.linspace(-1, 1, num=len(rvs)))`. Both Tree and Naive seem to recognize the variable bandwiths.

Am I missing something?


```python

import numpy as np
from KDEpy import NaiveKDE, TreeKDE
import matplotlib.pyplot as plt
from scipy.stats import lognorm

fig, axs = plt.subplots(2, 1, figsize=(9, 12))

# get a list of 1000 random variables from the scipy lognormal
# distribution with shape parameter 0.6
rvs = np.sort(lognorm.rvs(0.6, size=1000))
axs[0].plot(rvs, np.repeat(-0.01,len(rvs)), '|r', markersize=5, label='data')
axs[1].plot(rvs, np.repeat(-0.01,len(rvs)), '|r', markersize=5, label='data')

# get pdf of lognormal distribution
x = np.linspace(0, 7, 200)
pdf = lognorm.pdf(0.6, x)
axs[0].plot(x, pdf, 'r', alpha=0.5, label='Actual PDF')
axs[1].plot(x, pdf, 'r', alpha=0.5, label='Actual PDF')

# use a Silverman's long-tailed bandwidth as global_bw
IQR = np.percentile(rvs, q=75) - np.percentile(rvs, q=25)
global_bw = 0.79*IQR*len(rvs)**(-0.2)

# do fixed bandwidth kde's
fixed_naive_kde = NaiveKDE(kernel='gaussian', bw=global_bw).fit(rvs).evaluate(x)
fixed_tree_kde = TreeKDE(kernel='gaussian', bw=global_bw).fit(rvs).evaluate(x)
axs[0].plot(x, fixed_naive_kde, 'g', label='Fixed bandwidth NaiveKDE')
axs[0].plot(x, fixed_tree_kde, ':b', lw=3, label='Fixed bandwidth TreeKDE')

# input an array variable bandwiths
bws = 2 - np.abs(np.linspace(-1, 1, num=len(rvs))) 

var_naive_kde = NaiveKDE(kernel='gaussian', bw=bws).fit(rvs).evaluate(x)
var_tree_kde = TreeKDE(kernel='gaussian', bw=bws).fit(rvs).evaluate(x)
axs[1].plot(x, var_naive_kde, 'g', label='Variable bandwidth NaiveKDE')
axs[1].plot(x, var_tree_kde, ':b', lw=3, label='Variable bandwidth TreeKDE')

# compare to using the max of the variable bandwidths as the fixed bandwidth
max_tree_kde = TreeKDE(kernel='gaussian', bw=np.max(bws)).fit(rvs).evaluate(x)
axs[1].plot(x, max_tree_kde, ':m', lw=3, label='KDE using max')

axs[0].legend()
axs[1].legend()
plt.show()

```
![image](https://user-images.githubusercontent.com/10076072/100378499-893e3780-3013-11eb-9c62-1faf9864c6e9.png)

**Comment by inti-abbate** [comment] 2021-05-28 23:30
Hi @tommyod and @dkludwig! I'm using `KDEpy` for my work and it's very useful, thanks for it!

I had a similar issue and solved it by reinstalling `KDEpy` (with `pip install --force-reinstall KDEpy`), meaning you already fixed the bug in the last months.

Just for the record (and I apologize if I'm explaining something you already know), the bug was being caused by a line around line 153 of `BaseKDE.py` stating:
```
self.bw = bw
```
right after
```
if bw_to_scalar:
    bw = np.max(self.bw)
```
This, in addition to the fact that `NaiveKDE.evaluate` calls `super().evaluate` with `bw_to_scalar=False`, and  `TreeKDE.evaluate` doesn't, caused that a variable bandwith was replaced by its maximum when evaluating the TreeKDE. Now the statement `self.bw = bw` was removed so the issue was solved.

**Comment by tommyod** [comment] 2021-05-29 07:06
Thanks @inti-abbate . I'll close this issue now that it works :)

**Closed by tommyod** 2021-05-29 07:06 UTC

**Comment by dkludwig** [comment] 2021-05-29 13:31
Thanks @tommyod and @inti-abbate! I finished that part of the project I was working on, so I haven't needed this in a while, but I just tried it again and it works for me now as well! I think I must have missed @tommyod's first response, though, which might have helped me if I'd seen it back in November. In any case, thanks again!
