### ISSUE TITLE
Is it possible to fit and save the state of the FFTKDE?

### ISSUE THREAD

**Issue by KaizerJ** [tommyod/KDEpy#132] opened 2023-04-05 14:15 UTC
It is possible to fit and save the state of the FFTKDE to later evaluate on already fitted without the need of fitting every time?

**Comment by Hvass-Labs** [comment] 2023-04-19 09:47
I also need to save / load the KDE fit, because it is not practical for me to save the entire dataset. I also cannot use pickle, because I need to save the fitted model parameters in a database. And I need to save many thousands of these KDE models. So I would like to save the fitted model parameters e.g. as arrays of float-numbers.

The big packages like scipy, sklearn, and statsmodels can't save / load the KDE model parameters, apparently because they always need the entire dataset, even when sampling from the KDE density. Someone wrote somewhere that it is only possible with the FFT-version of KDE.

@tommyod I have taken a quick look at your code, and it looks well-made and documented. Kudos because it's rare that open-source code is so polished! But I don't really know how KDE works and I have a million other things to do, so is there a chance that you could make save / load functions for your FFT KDE? Is it difficult? Or do you simply not have the time right now, so I should look for another solution?

Thanks!

**Comment by syrte** [comment] 2023-04-19 11:31
I'd guess you just need to save the output arrays. 
They contains all the information you need.

**Comment by tommyod** [comment] 2023-04-19 12:41
@Hvass-Labs : thanks for the kind words. You have shared some great material too, and I think I stumbled upon your website or one of your repos years ago and it helped me.

My answer is that I never thought above this use case, and I will not attempt to implement anything clever for this use case. It's simply not what the library was designed to do, and unfortunately you're on your own. Some more information: the `fit` method is purely cosmetic, in the sense that no parameters are "learned". Is is when the `predict` method is called that a loop goes over all the data points (stored in the object during `fit` time), and interpolates them to the desired grid, then convolves the grid with a kernel. So fitting once and predicting twice is the same as fitting then predicting twice in terms of performance.

Hope that helps a little bit a least.

**Comment by Hvass-Labs** [comment] 2023-04-22 13:16
Thanks for the extremely quick replies and suggestions!

I decided to make an interpolator as @syrte suggested. I put the code on GitHub because I wasn't able to find this solution elsewhere:

https://github.com/Hvass-Labs/Code-Recipes

(I wonder if ChatGPT could have made this, I will have to give it a try.)

@tommyod I'm glad to hear you found my work useful! You are using what I call the "dual coding-style" where actual code is interleaved with extensive English comments. It is so much easier to read and understand. All my private code is also written like that. A lot of the big open-source projects are undocumented spaghetti-code that is impossible to understand, even for the devs who try to maintain them. Fortunately the "dual coding-style" with extensive English comments is getting more accepted and widespread. Undocumented code is either a lack of consideration for the reader, or it is a "nerdy macho thing" that people didn't want to "look stupid" by documenting their code properly.

(I suppose all this answers the OP's question so you can close this issue?)

**Closed** 2023-04-25 06:57 UTC
